# Generated by Django 5.2.1 on 2025-05-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='wish',
            table='Wishes',
        ),
    ]
